### ISSUE TITLE
Play command always returns "No search results found"

### ISSUE THREAD

**Issue by suvanl** [DS-Development/delet#20]
**Type**

- [ ] Suggestion
- [x] Bug

**Brief description of the problem**
Whenever the [`play`](https://github.com/DS-Development/delet/blob/master/music/js/audio.js#L30) command is run, and a number is provided to select a song from the song selection menu, delet will always respond with "No search results found".

**Expected behavior**
delet should play the selected song in the voice channel the author of the message is in.

**Actual behavior**
delet does not play the selected song, and instead, the command fails, by returning "No search results found".

**Steps to reproduce**
*Prerequisite: join a voice channel in which delet has permission to join and speak.*

1. Use the `play` command with all correct args, i.e. **`[prefix]play [song]`**
2. Select the number of the desired song, from the song selection menu
3. delet will return the "No search results found" message.

**Comment by suvanl** [comment]
The issue type has been identified, as a ReferenceError:
```js
ReferenceError: response is not defined
    at Client.client.on (<root>\music\js\audio.js:72:49)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

However, `response` *is* defined, and the **`play`** command has been working fine up until now, with no code changes being made... so why is there a `ReferenceError`?

**Comment by suvanl** [comment]
Identified as **not** being an API issue, as API requests are successfully being sent:
![API Requests](https://vgy.me/24znQc.png)

No errors have occurred for any of the requests.

Further proof that this isn't an API issue exists; the play command **does** return search results, but errors whilst attempting to play.

**Comment by suvanl** [comment]
The music system will be re-written soon, as some things in the current one aren't behaving as expected, as well as the issue of some of the code being slightly messy.

The new music system's commands may actually be implemented into the main bot, rather than having a separate module.
