### ISSUE TITLE
cannot find  enmap  , shows error

### ISSUE THREAD

**Issue by patilshreyas17** [DS-Development/delet#244]
this is errror i get  when i run the bot

internal/modules/cjs/loader.js:985    
  throw err;
  ^

Error: Cannot find module 'enmap'     
Require stack:
- C:\Users\lenovo\Desktop\bot\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\lenovo\Desktop\bot\index.js:21:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\lenovo\\Desktop\\bot\\index.js' ]
}
PS C:\Users\lenovo\Desktop\bot>

**Comment by suvanl** [comment]
hey, apologies for the massive delay.

did you run `npm install` (in the root directory) prior to attempting to run the bot?
also, what command did you enter into your terminal when attempting to run the bot?

**Comment by oodvg** [comment]
you need to install enmap. do npm install enmap -s
